apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: study-member-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/StudyHub-team3/StudyHub-backend-study-member.git
      targetRevision: HEAD
      path: .kube
    - repoURL: https://github.com/StudyHub-team3/StudyHub-kube-config.git
      targetRevision: feat/study-member
      path: services/study-member
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
