apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
data:
  application-jwt.yml: |
    jwt:
      header: Authorization
      secret-key: j0wt9f8ors76t5ud4yh2ub1j0wt9f8ors76t5ud4yh2ub1j0wt9f8ors76t5ud4yh2ub1j0wt9f8ors76t5ud4yh2ub1j0wt9f8ors76t5ud4yh2ub1j0wt9f8ors76t5ud4yh2ub1j0wt9f8ors76t5ud4yh2ub1
      # 보안이 필요한 상황에서는 변경해서 사용