apiVersion: v1
kind: Secret
metadata:
  name: mysql-jdbc-secret-volume
type: Opaque
stringData:
  application-mysql.yml: |
    spring:
      datasource:
        username: user
        password: 1234 #TODO 개인 로컬 환경에 따라 변경
