apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
stringData:
  application-redis.yml: |
    spring:
      data:
        redis:
          host: redis-external-service
          port: 6379